proxy:
  title: SPC apps
  template-path: /home/os/eSPC_biophysics_platform/templates/custom
  favicon-path:  /home/os/eSPC_biophysics_platform/custom/favicon.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: none
  hide-navbar: true

# Docker configuration
  docker:
    # cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000

  specs:
    - id: moltenprot
      display-name: MoltenProt
      container-cmd: ["R", "-e", "shiny::runApp('/home/shiny/MoltenProt')"]
      container-image: spc_apps_docker_container

    - id: foldAffinity
      display-name: FoldAffinity
      container-cmd: ["R", "-e", "shiny::runApp('/home/shiny/FoldAffinity')"]
      container-image: spc_apps_docker_container

    - id: thermoAffinity
      display-name: ThermoAffinity
      container-cmd: ["R", "-e", "shiny::runApp('/home/shiny/ThermoAffinity')"]
      container-image: thermo_affinity

    - id: photoMol
      display-name: PhotoMol
      container-cmd: ["R", "-e", "shiny::runApp('/home/shiny/PhotoMol')"]
      container-image: photo_mol

    - id: raynals
      display-name: Raynals
      container-cmd: ["R", "-e", "shiny::runApp('/home/shiny/Raynals')"]
      container-image: raynals

    - id: chirakit
      display-name: ChiraKit
      container-cmd: ["R", "-e", "shiny::runApp('/home/shiny/ChiraKit')"]
      container-image: chirakit

logging:
  file:
    /tmp/shinyproxy.log

