box(title = "Plot options", width = 7, solidHeader = T, status = "primary", 
    fluidRow(
      
      column(2, p(HTML("<b>Show Advanced</b>"),
                  checkboxInput("show_plot_download_options_input", "", FALSE))),
      
      column(2, p(HTML("<b>Plot type</b>"),
                  selectInput("plot_type_hr_distribution", NULL,
                              c("Histogram"  = "histogram",
                                "Viridis"   = "rainbow",
                                "Gray"      = "gray",
                                "Dual"      = "dual"
                                )))),
      
      column(2, p(HTML("<b>Relative height</b>"),
                  span(shiny::icon("info-circle"), id = "info_uu_OverlapFactor"),
                  numericInput('overlapFactor',NULL, 3,min = 0, max = 100),
                  tippy::tippy_this(elementId = "info_uu_OverlapFactor",
                                    tooltip = "Decide how much the Rh distribution
                                    curves overlap.",placement = "right"))),
      
      column(2, p(HTML("<b>Distribution</b>"),
                  span(shiny::icon("info-circle"), id = "info_uu_distribution_type"),
                  selectInput("distribution_type", NULL,
                              c("Rh"   = "hr",
                                "Diff" = "diff")),
                  tippy::tippy_this(elementId = "info_uu_distribution_type",
                  tooltip = "Analyse the
                  relative contributions as a function of hydrodynamic radii (Rh)
                  or diffusion coefficients. Take into account that
                  the Rh values depend on the temperature and viscosity 
                  of the experiment.",placement = "right"))),
      
      column(2, p(HTML("<b>Peak filter</b>"),
                  span(shiny::icon("info-circle"), id = "info_uu_peak_filter"),
                  checkboxInput("peak_filter", "", FALSE),
                  tippy::tippy_this(elementId = "info_uu_peak_filter",
                  tooltip = "Apply this filter to avoid plotting data with intensity < 1 %. Useful to remove
                  small peaks which may have been artificially generated by the 
                  fitting algorithm.",placement = "right"))),
      
      conditionalPanel(condition = "input.show_plot_download_options_input",

         column(2, p(HTML("<b>File type</b>"),
                     selectInput("plot_type", NULL,
                                 c("PNG"    = "png",
                                   "SVG"    = "svg",
                                   "JPEG"    = "jpeg"))))  
                                            
      )),
  
    fluidRow(
      
      conditionalPanel(condition = "input.show_plot_download_options_input",
                       
                       column(2, p(HTML("<b>Width</b>"),
                                   span(shiny::icon("info-circle"), id = "info_uu1-13"),
                                   numericInput('plot_width',NULL, 12,min = 1, max = 100),
                                   tippy::tippy_this(elementId = "info_uu1-13",
                                                     tooltip = "Units are pixels * 50",placement = "right"))),
                       
                       column(2, p(HTML("<b>Height</b>"),
                                   span(shiny::icon("info-circle"), id = "info_uu1-14"),
                                   numericInput('plot_height',NULL, 11,min = 1, max = 100),
                                   tippy::tippy_this(elementId = "info_uu1-14",
                                                     tooltip = "Units are pixels * 50",
                                                     placement = "right"))),                     
                       
                       column(2, p(HTML("<b>Row order</b>"),
                                   selectInput(
                                     "rowOrder", NULL,c(
                                       "Default"      =  "default",
                                       "Alphanumeric" =  "alphanumeric")))),
                       
                       column(2, p(HTML("<b>Axis text size</b>"),
                                   numericInput('plot_axis_size',NULL, 16,min = 4, max = 40))),
                       
                       column(2, p(HTML("<b>Log Axis type</b>"),
                                   selectInput("logScaleType", NULL,
                                               c("Microseconds"     =  "microseconds",
                                                 "Miliseconds"      =  "miliseconds",
                                                 "Seconds"          =  "seconds",
                                                 "Default Plotly" =  "defaultPlotly")))),
                       
                       column(2, p(HTML("<b>Residuals plot</b>"),
                                   selectInput("residualsPlotSelection", NULL,
                                               c("None"        =  "None"))))
                       
      )),
      
    fluidRow(
      
      conditionalPanel(condition = "input.show_plot_download_options_input",
      
         column(2,p(HTML("<b></b>"),
                    span(shiny::icon("info-circle"), id = "info_uu222-5"),
                    withBusyIndicatorUI(downloadButton("download_plots", "Plots")),
                    tippy::tippy_this(elementId = "info_uu222-5",
                                      tooltip = "Create a zip file containing the estimated hydrodynamic radius 
                                      distributions. This button will not export 'collapsed' plots.",
                                      placement = "right")))
      )
))



