FROM rocker/r2u:24.04 AS builder

LABEL maintainer="oburastero@gmail.com"

COPY /kineticsApp/appFiles/Rprofile.site /usr/lib/R/etc/Rprofile.site

# Additional packages required for Python installation
ARG PYTHON_PACKAGES="python3 python3-pip python3-venv python3-dev"

ARG R_PACKAGES="reticulate shiny shinyjs shinydashboard shinycssloaders shinyalert \
tippy rhandsontable plotly reshape2 tidyverse DT colourpicker"

RUN apt-get update && apt-get install --no-install-recommends --yes $PYTHON_PACKAGES && \
    install.r $R_PACKAGES                                                            && \
    apt-get autoclean                                                                && \
    useradd -ms /bin/bash  shiny

COPY /kineticsApp/appFiles/requirements.txt   requirements.txt

# Switch to the shiny user
USER shiny

RUN python3 -m venv /home/shiny/myenv && \
    /home/shiny/myenv/bin/pip install --prefer-binary --no-cache-dir -r requirements.txt


FROM builder AS build2

COPY --chown=shiny:shiny /kineticsApp/appFiles/  /home/shiny/

USER ROOT
EXPOSE 3838
USER shiny

CMD ["R", "-e", "shiny::runApp('/home/shiny/KinGenie')"]