FROM rocker/r2u:24.04 AS builder

MAINTAINER Osvaldo Burastero "oburastero@gmail.com"

COPY /circularDichroismApp/appFiles/Rprofile.site /usr/lib/R/etc/Rprofile.site

# Additional packages required for Python installation
ARG PYTHON_PACKAGES="python3 python3-pip python3-venv python3-dev"

ARG R_PACKAGES="reticulate tidyverse shiny factoextra shinydashboard shinycssloaders tippy \
rhandsontable colourpicker plotly reshape2 DT signal ggdendro quadprog shinyalert"

ARG BUILD_PACKAGES="pandoc"

RUN apt-get update && apt-get install --no-install-recommends --yes $BUILD_PACKAGES $PYTHON_PACKAGES && \
    install.r $R_PACKAGES                                                                            && \
    apt-get autoclean                                                                                && \
    useradd -ms /bin/bash  shiny                                                                     
            
COPY /circularDichroismApp/appFiles/mkdssp-4.4.0-linux-x64   mkdssp-4.4.0-linux-x64

RUN chmod +x mkdssp-4.4.0-linux-x64    && \
    mv mkdssp-4.4.0-linux-x64 /usr/local/bin/ 

COPY /circularDichroismApp/appFiles/requirements.txt   requirements.txt
 
USER shiny

RUN python3 -m venv /home/shiny/myenv && \
    /home/shiny/myenv/bin/pip install --prefer-binary --no-cache-dir -r requirements.txt

FROM builder AS build2

COPY --chown=shiny:shiny /circularDichroismApp/appFiles/   /home/shiny/

RUN python3 /home/shiny/ChiraKit/SESCA_v097/setup.py @prefix /home/shiny/ChiraKit/SESCA_v097 @source /home/shiny/ChiraKit/SESCA_v097

USER ROOT
EXPOSE 3838 
USER shiny

                                           
CMD ["R", "-e", "shiny::runApp('/home/shiny/ChiraKit')"]