FROM rocker/r2u:24.04 AS builder

MAINTAINER Osvaldo Burastero "oburastero@gmail.com"

COPY /thermoA_app/Rprofile.site /usr/lib/R/etc/Rprofile.site

# Additional packages required for Python installation
ARG PYTHON_PACKAGES="python3 python3-pip python3-venv python3-dev"

ARG R_PACKAGES="shiny tidyverse reshape2 reticulate shinyjs shinydashboard shinycssloaders shinyalert  \
tippy rhandsontable plotly minpack.lm nlstools broom data.table colourpicker RColorBrewer"

RUN apt-get update && apt-get install --no-install-recommends --yes $PYTHON_PACKAGES && \
    install.r $R_PACKAGES                                                            && \
    apt-get autoclean                                                                && \
    useradd -ms /bin/bash  shiny 

COPY /thermoA_app/requirements.txt   requirements.txt

# Switch to the shiny user
USER shiny

RUN python3 -m venv /home/shiny/myenv && \
    /home/shiny/myenv/bin/pip install --prefer-binary --no-cache-dir -r requirements.txt

FROM builder AS build2

COPY --chown=shiny:shiny /thermoA_app/   /home/shiny/

USER ROOT
EXPOSE 3838 
USER shiny
                                           
CMD ["R", "-e", "shiny::runApp('/home/shiny/thermoAffinity')"]