FROM rocker/r2u:24.04 AS builder

LABEL maintainer="oburastero@gmail.com"

COPY /differentialScanningFluorimetryApps/appFiles/Rprofile.site /usr/lib/R/etc/Rprofile.site

# Additional packages required for Python installation
ARG PYTHON_PACKAGES="python3 python3-pip python3-venv python3-dev"

ARG R_PACKAGES="tableHTML tidyverse pracma reshape2 data.table reticulate shinyjs shinydashboard \
shinycssloaders shinyalert tippy rhandsontable plotly grid tinytex egg ggpubr viridis minpack.lm \
broom Cairo"

ARG BUILD_PACKAGES="pandoc"

RUN apt-get update && apt-get install --no-install-recommends --yes $BUILD_PACKAGES $PYTHON_PACKAGES && \
    install.r $R_PACKAGES                                                                            && \
    apt-get autoclean                                                                                && \
    useradd -ms /bin/bash  shiny                                                                     

COPY /differentialScanningFluorimetryApps/appFiles/requirements.txt   requirements.txt

USER shiny

RUN python3 -m venv /home/shiny/myenv && \
    /home/shiny/myenv/bin/pip install --prefer-binary --no-cache-dir -r requirements.txt             && \
    R -e 'tinytex::install_tinytex()'                                                                && \
    R -e "tinytex::parse_install(text = \"! LaTeX Error: File \`fancyhdr.sty\' not found.\")" 

FROM builder AS build2

COPY --chown=shiny:shiny /differentialScanningFluorimetryApps/appFiles/   /home/shiny/

USER ROOT
EXPOSE 3838 
USER shiny
                                           
CMD ["R", "-e", "shiny::runApp('/home/shiny/MoltenProt')"]
