FROM r-base:4.3.2 AS builder

MAINTAINER Osvaldo Burastero "oburastero@gmail.com"

COPY /refeynApp/install_r_packages.R /refeynApp/Rprofile.site  ./

ARG BUILD_PACKAGES="sudo cmake pandoc libxml2 libxml2-dev \ 
libcurl4-gnutls-dev libcairo2-dev/unstable     \ 
libxt-dev libssl-dev liblzma-dev libbz2-dev default-jdk   \
libharfbuzz-dev libfribidi-dev   \
libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev"

RUN apt-get update && apt-get install --no-install-recommends --yes  $BUILD_PACKAGES && \
    R CMD javareconf                                                                 && \
    install2.r --error rJava                                                         && \
    mv Rprofile.site /usr/lib/R/etc/                                                 && \
    Rscript install_r_packages.R                                                     && \
    apt-get autoclean                                                                && \
    rm -rf /tmp/downloaded_packages/ /tmp/*.rds                                      && \
    rm -rf /var/lib/apt/lists/*                                                      && \    
    useradd -ms /bin/bash  shiny                                                     

USER shiny

RUN wget --no-verbose https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  -P /home/shiny/               && \
    bash  /home/shiny/Miniconda3-latest-Linux-x86_64.sh -b                                                                && \
    rm -f /home/shiny/Miniconda3-latest-Linux-x86_64.sh                                                                   && \
    /home/shiny/miniconda3/bin/conda clean --all -y                                                                       && \
    rm -rf /install/conda/pkgs/*/info                                                                                     && \
    /home/shiny/miniconda3/bin/conda  create --name r-reticulate                                                          && \   
    /home/shiny/miniconda3/bin/conda  install   --freeze-installed -n r-reticulate -c anaconda nomkl           && \            
    /home/shiny/miniconda3/bin/conda  install   --freeze-installed -n r-reticulate -c anaconda numpy    && \ 
### Uncomment/modify the next lines if you plan to install python packages    
    /home/shiny/miniconda3/bin/conda  install   --freeze-installed -n r-reticulate -c anaconda pandas    && \
    /home/shiny/miniconda3/bin/conda  install   --freeze-installed -n r-reticulate -c anaconda scipy     && \
    /home/shiny/miniconda3/bin/conda  install   --freeze-installed -n r-reticulate -c anaconda h5py     && \
    /home/shiny/miniconda3/bin/conda  install   --freeze-installed -n r-reticulate -c anaconda xlrd     && \
    /home/shiny/miniconda3/bin/conda clean -afy                                                                           && \
    find /home/shiny/miniconda3/ -follow -type f -name '*.a'      -delete      && \
    find /home/shiny/miniconda3/ -follow -type f -name '*.pyc'    -delete      && \
    find /home/shiny/miniconda3/ -follow -type f -name '*.js.map' -delete      && \
    mkdir -p /home/shiny/data_users                                                                                       

FROM builder AS build2

COPY /refeynApp/ ./
USER root
RUN mv PhotoMol/   /home/shiny/    

EXPOSE 3838
USER shiny
                                           
CMD ["R", "-e", "shiny::runApp('/home/shiny/PhotoMol')"]
