FROM rocker/r2u:26.04 AS builder

LABEL maintainer="oburastero@gmail.com"

COPY /circularDichroismApp/appFiles/Rprofile.site /usr/lib/R/etc/Rprofile.site

ARG PYTHON_PACKAGES="python3 python3-pip python3-venv python3-dev"
ARG R_PACKAGES="reticulate tidyverse shiny shinydashboard shinycssloaders tippy rhandsontable colourpicker plotly reshape2 DT signal ggdendro shinyalert"
ARG BUILD_PACKAGES="pandoc"

RUN apt-get update && apt-get install --no-install-recommends --yes \
    $BUILD_PACKAGES $PYTHON_PACKAGES && \
    install.r $R_PACKAGES && \
    rm -rf /var/lib/apt/lists/* && \
    useradd -ms /bin/bash shiny

COPY /circularDichroismApp/appFiles/mkdssp-4.4.0-linux-x64 /usr/local/bin/mkdssp-4.4.0-linux-x64
RUN chmod +x /usr/local/bin/mkdssp-4.4.0-linux-x64

COPY /circularDichroismApp/appFiles/requirements.txt /tmp/requirements.txt

RUN python3 -m venv /home/shiny/myenv && \
    /home/shiny/myenv/bin/python -m pip install --upgrade pip setuptools wheel && \
    /home/shiny/myenv/bin/pip install --prefer-binary --no-cache-dir -r /tmp/requirements.txt && \
    chown -R shiny:shiny /home/shiny/myenv

COPY --chown=shiny:shiny /circularDichroismApp/appFiles/ /home/shiny/

RUN python3 /home/shiny/ChiraKit/SESCA_v097/setup.py @prefix /home/shiny/ChiraKit/SESCA_v097 @source /home/shiny/ChiraKit/SESCA_v097

USER root
EXPOSE 3838
USER shiny

CMD ["R", "-e", "shiny::runApp('/home/shiny/ChiraKit')"]